const express = require('express');
const router = express.Router();
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const jobRoutes = require('./job.routes');
const categoryRoutes = require('./category.routes');
const companyRoutes = require('./company.routes');
const websiteSettingRoutes = require('./websiteSetting.routes');
const pageSeoRoutes = require('./pageSeo.routes');
const adRoutes = require('./ad.routes');
const adsConfigRoutes = require('./adsConfig.routes');
const analyticsRoutes = require('./analytics.routes');
const sitemapRoutes = require('./sitemap.routes');
const aboutRoutes = require('./about.routes');
const contactRoutes = require('./contact.routes');
const adminRoutes = require('./admin.routes');
const seoRoutes = require('./seo.routes');
const notificationRoutes = require('./notification.routes');
const schemaRoutes = require('./schema.routes');
const searchConsoleRoutes = require('./searchConsole.routes');

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/jobs', jobRoutes);
router.use('/categories', categoryRoutes);
router.use('/companies', companyRoutes);
router.use('/website-settings', websiteSettingRoutes);
router.use('/page-seo', pageSeoRoutes);
router.use('/ads', adRoutes);
router.use('/', adsConfigRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/sitemap', sitemapRoutes);
router.use('/about', aboutRoutes);
router.use('/contact', contactRoutes);
router.use('/admin', adminRoutes);
router.use('/seo', seoRoutes);
router.use('/notifications', notificationRoutes);
router.use('/schema', schemaRoutes);
router.use('/search-console', searchConsoleRoutes);

module.exports = router; 